Repository tnpfldyd/semi_pjt_2, pull requests merged in 2022-11, with the labels that each got.

#56 test tag
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_remove_user_card_created.py
  cards/migrations/0001_initial.py
  cards/migrations/0002_auto_20221115_1410.py
  cards/migrations/0002_groupcard.py
  cards/migrations/0003_auto_20221115_1340.py
  cards/migrations/0004_groupcomment.py
  cards/migrations/0005_alter_groupcomment_groupcard.py
  cards/migrations/0006_alter_groupcard_user.py
  cards/views.py
  meetings/migrations/0001_initial.py
  meetings/migrations/0002_rename_meeting_id_comment_meeting.py
  vocies/migrations/0001_initial.py
Labels: bug

#58 group card
  accounts/migrations/0001_initial.py
  cards/migrations/0001_initial.py
  cards/templates/cards/group_detail.html
  cards/templates/cards/groupcard_update.html
  cards/templates/cards/index.html
  cards/urls.py
  cards/views.py
  meetings/migrations/0001_initial.py
Labels: enhancement

#60 add/notes
  accounts/views.py
  meetings/templates/meetings/index.html
  notes/__init__.py
  notes/admin.py
  notes/apps.py
  notes/forms.py
  notes/migrations/0001_initial.py
  notes/migrations/__init__.py
  notes/models.py
  notes/templates/notes/detail.html
  notes/templates/notes/index.html
  notes/templates/notes/send.html
  notes/tests.py
  notes/urls.py
  notes/views.py
  semi_pjt_2/settings.py
  semi_pjt_2/urls.py
Labels: documentation

#62 bugfix
  cards/urls.py
Labels: bug

#65 Meeting
  meetings/templates/meetings/index.html
  static/style.css
Labels: enhancement

#67 notes
  meetings/templates/meetings/index.html
  notes/templates/notes/detail.html
  notes/templates/notes/index.html
  notes/templates/notes/send.html
  static/style.css
Labels: enhancement

#68 Update/accounts
  accounts/migrations/0002_auto_20221116_1029.py
  accounts/models.py
  accounts/templates/accounts/mypage.html
  accounts/urls.py
  accounts/views.py
  cards/forms.py
  cards/migrations/0005_auto_20221116_1629.py
  cards/migrations/0006_alter_usercard_user.py
  cards/models.py
  cards/views.py
  meetings/templates/meetings/index.html
Labels: documentation

#69 그룹 기능 + 프로필 미완
  accounts/templates/accounts/profile.html
  accounts/urls.py
  accounts/views.py
  cards/templates/cards/group_detail.html
  cards/templates/cards/index.html
  cards/urls.py
  cards/views.py
  static/images/santabag.png
  static/images/산타가방.png
  static/js/fireplace.js
  static/style.css
Labels: enhancement

#72 Update/mypage
  accounts/templates/accounts/mypage.html
  templates/base.html
Labels: bug

#76 저장 전 커밋
  cards/templates/cards/index.html
  cards/views.py
  static/style.css
Labels: invalid

#77 card 전환 애니메이션 추가
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_auto_20221116_1029.py
  cards/migrations/0001_initial.py
  cards/migrations/0007_alter_usercard_user.py
  cards/templates/cards/group_detail.html
  cards/views.py
  meetings/migrations/0001_initial.py
  notes/migrations/0001_initial.py
  static/images/rudolph.gif
  static/js/fireplace.js
  static/style.css
  static/style_card.css
Labels: enhancement

#79 Commit
  meetings/templates/meetings/detail.html
  meetings/templates/meetings/index.html
Labels: enhancement

#81 profilefix
  accounts/urls.py
  cards/templates/cards/index.html
  cards/templates/cards/indiv_detail.html
  cards/views.py
  meetings/views.py
Labels: bug

#85 Update/notice
  accounts/migrations/0002_user_notice.py
  accounts/models.py
  accounts/templates/accounts/profile.html
  cards/views.py
  notes/views.py
Labels: invalid

#93 profilepush
  cards/migrations/0002_alter_usercard_chimneys.py
  cards/migrations/0003_alter_usercard_chimneys.py
  cards/migrations/0004_rename_ribbons_usercomment_socks.py
  cards/models.py
  cards/templates/cards/usercard_comment.html
  cards/templates/cards/usercard_create.html
  cards/views.py
  static/images/양말1.png
  static/images/양말10.png
  static/images/양말11.png
  static/images/양말12.png
  static/images/양말2.png
  static/images/양말3.png
  static/images/양말7.png
  static/images/양말8.png
  static/images/양말9.png
  static/style.css
Labels: 메리크리스마스

#95 card css 추가 - 미완
  cards/templates/cards/create_group.html
  cards/templates/cards/group_detail.html
  cards/templates/cards/groupcard_update.html
  cards/templates/cards/index.html
  static/style_card.css
Labels: 임시

#96 Update/accounts/update
  accounts/forms.py
  accounts/templates/accounts/update.html
  accounts/views.py
  meetings/templates/meetings/index.html
Labels: Update

#98 follow/update
  meetings/templates/meetings/index.html
Labels: Update

#99 notes design
  accounts/templates/accounts/profile.html
  cards/migrations/0001_initial.py
  cards/migrations/0002_alter_usercard_chimneys.py
  cards/migrations/0003_alter_usercard_chimneys.py
  cards/migrations/0004_rename_ribbons_usercomment_socks.py
  notes/templates/notes/detail.html
  notes/templates/notes/index.html
  notes/templates/notes/send.html
  notes/views.py
  static/images/쪽지배경.png
  static/style.css
Labels: enhancement

#103 css design
  accounts/templates/accounts/block_user.html
  accounts/templates/accounts/mypage.html
  accounts/views.py
  meetings/templates/meetings/index.html
  meetings/views.py
Labels: enhancement

#111 meeting detail
  meetings/templates/meetings/detail.html
  meetings/templates/meetings/index.html
  meetings/urls.py
  meetings/views.py
  static/style.css
Labels: bug

#120 Update/meeting
  accounts/templates/accounts/test.html
  accounts/views.py
  meetings/templates/meetings/index.html
  meetings/templatetags/__init__.py
  meetings/templatetags/custom_tags.py
  meetings/views.py
  static/css/base.css
  static/css/base.css.map
  static/css/base.scss
  templates/base.html
Labels: bug

#121 serach 페이지네이션 구현 중
  cards/templates/cards/index.html
  cards/templates/cards/search.html
  cards/urls.py
  cards/views.py
Labels: 임시

#122 Update/meetings
  cards/migrations/0001_initial.py
  cards/migrations/0002_auto_20221119_2012.py
  cards/migrations/0002_auto_20221119_2323.py
  cards/migrations/0003_rename_userdeco_groupcard_groupdeco.py
  cards/templates/cards/search.html
  cards/views.py
Labels: bug

#124 Update/usercard_detail
  cards/templates/cards/usercard_detail.html
  static/css/profile.css
  templates/base.html
Labels: Update

#129 Update/search
  cards/templates/cards/search.html
  cards/views.py
Labels: Update

#130 그룹카드 프사 수정
  cards/templates/cards/index.html
Labels: hotfix

#134 개인카드 애니메이션
  cards/migrations/0002_auto_20221120_1601.py
  cards/models.py
Labels: 임시

#135 숨쉬기 추가
  cards/templates/cards/usercard_detail.html
Labels: enhancement

#145 hotfix 카드오픈
  cards/views.py
Labels: hotfix
